apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
  labels:
    project: banking-app
    environment: production
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: banking-app
    version: blue  # Default to blue; this can be switched to green during deployment
